### PCA is used for noise reduction , the goal of this project is to see how PCA can help to reduce the noise of handwritten digits in order to classify them

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_image=pd.read_csv('noisy_digits.csv')
data_image.head()

Unnamed: 0      pixel0      pixel1      pixel2      pixel3      pixel4  \
0           0 -176.321245  -52.743850  143.604939  -53.567749   80.289381   
1           1 -158.421239   16.371695   62.810879  263.533916 -193.920320   
2           2 -290.343750   81.586500   12.615232  146.567851  111.233602   
3           3 -208.840590  136.190431   38.552191  -67.825346   24.316303   
4           4 -328.876288  -42.862900  174.651874 -228.833439   71.909654   

       pixel5      pixel6      pixel7      pixel8  ...    pixel774  \
0   20.686379 -197.423519 -229.401206 -221.900009  ...   34.407070   
1  -25.366668  107.062706  125.403427   83.536343  ...   -5.419961   
2 -188.989259 -101.464605 -107.015195  -13.069827  ... -139.909318   
3  176.103673   31.581298 -163.582673   29.777077  ... -131.385192   
4  -97.206392   48.048853  -34.071313    3.820465  ... -135.713199   

     pixel775    pixel776    pixel777    pixel778    pixel779    pixel780  \
0    1.950735  -25.095565  133.684095  -21.664094  -94.305438  -55.987821   
1 -123.584030   20.240434  -25.699206 -128.545930   52.525885  -54.214887   
2  -85.214133  167.495617   62.402411 -144.402970  152.263950   -4.687051   
3   40.329733  -10.111639  163.497435   41.010287  -21.408008  328.274235   
4  -71.396796  155.237981 -141.860908  155.657335  166.609760  -52.911774   

     pixel781    pixel782    pixel783  
0  -89.929231   40.394774 -214.754480  
1 -133.842624  -30.141215  210.408665  
2  -59.270131  -93.193600  188.229794  
3  -15.341672  121.570863  151.757537  
4  267.150703  -36.749672  131.913772  

[5 rows x 785 columns]

In [3]:
data_labels=pd.read_csv('noisy_digits_labels.csv')
data_labels.head()

Unnamed: 0  label
0           0      1
1           1      0
2           2      1
3           3      4
4           4      0

In [4]:
#Shape of the dataset
print("The shape of the dataset is :")
display(data_image.shape)
#The columns of the dataset
print("The columns of the dataset :")
display(data_image.columns)
#The type of the columns of the dataset 
print("The Type of columns of the dataset :")
display(data_image.dtypes)
#Some statistical information about the dataset
print(" Some statistical information about the dataset :")
display(data_image.describe(include="all"))
#The pourcentage of missing value in the columns of the dataset
print(" The pourcentage of missing value in the columns of the dataset:")
display(100*data_image.isnull().sum()/data_image.shape[0])

The shape of the dataset is :


(42000, 785)

The columns of the dataset :


Index(['Unnamed: 0', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4',
       'pixel5', 'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

The Type of columns of the dataset :


Unnamed: 0      int64
pixel0        float64
pixel1        float64
pixel2        float64
pixel3        float64
               ...   
pixel779      float64
pixel780      float64
pixel781      float64
pixel782      float64
pixel783      float64
Length: 785, dtype: object

 Some statistical information about the dataset :


Unnamed: 0        pixel0        pixel1        pixel2        pixel3  \
count  42000.00000  42000.000000  42000.000000  42000.000000  42000.000000   
mean   20999.50000      0.508865      0.161267     -0.136474      0.504606   
std    12124.49999    125.424203    125.957019    124.814080    124.209803   
min        0.00000   -536.272379   -563.581377   -596.266187   -515.063938   
25%    10499.75000    -83.800118    -84.915914    -84.807013    -82.854817   
50%    20999.50000      0.860217      0.886333      0.763704      1.024988   
75%    31499.25000     84.104507     84.746673     84.124227     84.558812   
max    41999.00000    498.641540    521.528036    505.180363    497.784712   

             pixel4        pixel5        pixel6        pixel7        pixel8  \
count  42000.000000  42000.000000  42000.000000  42000.000000  42000.000000   
mean      -0.392227     -1.146996      0.065945     -0.932743      1.202804   
std      125.421539    125.156993    124.927893    124.995896    125.198035   
min     -532.306749   -513.457210   -543.357776   -537.067105   -487.779478   
25%      -85.834707    -84.970270    -83.641462    -85.161672    -82.887900   
50%       -0.613646     -0.942170      0.750785     -1.703407      1.237868   
75%       84.176809     83.098343     84.426144     83.654107     85.635613   
max      557.447725    496.639090    502.002720    511.211431    501.472247   

       ...      pixel774      pixel775      pixel776      pixel777  \
count  ...  42000.000000  42000.000000  42000.000000  42000.000000   
mean   ...      0.329851      0.121329     -0.655444     -0.100407   
std    ...    124.154492    124.397062    124.896809    124.596065   
min    ...   -461.635368   -506.789421   -474.601499   -499.907780   
25%    ...    -84.349026    -83.802971    -85.491390    -84.701319   
50%    ...     -0.523211      0.359867      0.253873     -0.603624   
75%    ...     84.494976     85.120277     83.715392     83.297809   
max    ...    496.220224    506.105780    608.211734    533.828554   

           pixel778      pixel779      pixel780      pixel781      pixel782  \
count  42000.000000  42000.000000  42000.000000  42000.000000  42000.000000   
mean       0.276097     -0.140400     -0.625908      1.870961     -0.466101   
std      124.836661    125.616450    124.783298    125.710628    125.456830   
min     -509.357382   -525.725612   -535.190814   -504.797562   -511.439969   
25%      -84.307686    -84.130186    -84.127703    -83.530383    -84.919834   
50%        0.632699     -0.794485     -0.848120      1.677145     -1.445551   
75%       85.881156     84.257741     84.000764     86.770448     83.957442   
max      585.756919    484.635537    471.135960    581.003313    505.345850   

           pixel783  
count  42000.000000  
mean      -0.757627  
std      125.542711  
min     -519.477568  
25%      -85.620350  
50%       -0.848889  
75%       84.193126  
max      515.791515  

[8 rows x 785 columns]

 The pourcentage of missing value in the columns of the dataset:


Unnamed: 0    0.0
pixel0        0.0
pixel1        0.0
pixel2        0.0
pixel3        0.0
             ... 
pixel779      0.0
pixel780      0.0
pixel781      0.0
pixel782      0.0
pixel783      0.0
Length: 785, dtype: float64

### Dropping the first column from  both datasets

In [5]:
data_labels = data_labels.drop('Unnamed: 0', axis=1)
data_image = data_image.drop('Unnamed: 0', axis=1)

In [6]:
display(data_labels.columns)
display(data_image.columns)

Index(['label'], dtype='object')

Index(['pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=784)

### Visualizing images by using numpy and plotly

In [7]:
!pip install --upgrade plotly

In [9]:
# Import plotly
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import warnings
warnings.filterwarnings("ignore")


fig = px.imshow(data_image.values[0:10].reshape(10, 28, 28), binary_string=True, facet_col=0, facet_col_wrap=5)
fig.show()

### Using train_test_split from sklearn to split the dataset into a train and a test set.

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_image, data_labels, random_state=0)
X_train.head()


pixel0      pixel1      pixel2      pixel3      pixel4      pixel5  \
5837    24.289180   45.983646  256.352134  -26.261889   11.683430 -205.429795   
26919  100.230434   44.166899  186.224206  307.291983 -266.608791  174.360175   
15177  -47.699431 -167.740414  238.069692  -98.327298 -224.500853   67.918157   
14046  -11.944284 -209.514843  113.523511   -5.111774  182.322677   73.826136   
22315  -85.086368 -133.186743  142.284695 -189.976676 -278.072652  130.695004   

           pixel6      pixel7      pixel8      pixel9  ...    pixel774  \
5837  -137.313894   29.045135   95.337022  -90.620796  ...   13.850705   
26919 -134.828176  215.091557 -205.003950  181.104424  ...  143.917566   
15177    1.317024   52.201427  117.235908   13.082838  ...   62.499730   
14046  -77.099973  102.352925   60.394222  149.039467  ... -174.471094   
22315   91.594462   33.159837  124.973469 -269.550718  ...   23.206283   

         pixel775    pixel776    pixel777    pixel778    pixel779    pixel780  \
5837    50.352009  -28.988928   57.604085   36.024349   15.966126    9.261994   
26919  -33.805104    2.545959  -60.373496   65.902161 -185.317670  156.806654   
15177  -78.223355  187.178508 -149.544457  186.401464  -55.541073  103.616753   
14046   42.355302   91.010817  -54.704095  -90.580398   81.801558   16.496764   
22315 -227.845723  -64.189901 -132.225714 -126.693863  -76.637899   32.982080   

         pixel781    pixel782    pixel783  
5837   126.795466 -181.947605 -103.029471  
26919   -9.674685 -117.225176   47.191232  
15177  318.404856 -229.352298  -34.503929  
14046  -49.476950  253.968096   61.867205  
22315 -144.533851  116.305279  -75.537392  

[5 rows x 784 columns]

### Normalizing the dataset

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_sc_train = sc.fit_transform(X_train)
X_sc_test = sc.transform(X_test)

### Training SVM model to classify the images 

In [14]:
from sklearn.svm import SVC
svc = SVC(random_state=0, verbose=True)
svc.fit(X_sc_train, y_train)
display(svc.score(X_sc_test, y_test))

[LibSVM]

0.886

### Using PCA for noise cancellation

In [20]:
from sklearn.decomposition import PCA
# Create a PCA instance with a 10% variance explained threshold
#The specified threshold of 10% means that I want to 
#retain principal components that collectively explain at least 10% of the total variance in the data.
pca = PCA(.10)
X_pca_train = pca.fit_transform(X_sc_train)
X_pca_train[:5]

array([[-5.96208316, -0.42351373,  0.44470052,  0.57060786,  2.95242258,
        -1.17188072,  1.05069839, -0.13964367, -1.40303368, -2.92619999,
         0.38387206,  1.57951042, -0.54456549],
       [ 0.56433535, -1.22875461,  1.80909413, -2.79629372, -4.66531164,
         0.60056317, -1.57775989, -2.22058894, -0.82044612, -0.44829183,
         0.40847823, -1.15397558,  2.00880282],
       [-2.74876075,  0.57114036, -3.51933441, -1.01876267,  0.62326501,
         0.82822044, -0.02896527, -0.4580741 , -0.16667535,  4.56519067,
         0.75325915,  0.89821879, -0.92016151],
       [-2.35736473, -0.12577577, -1.94688851,  1.68370608, -4.65432857,
         5.51621668, -1.15504779,  1.41742162, -3.18671343,  2.80454839,
         0.6841405 ,  0.05205339,  0.63961574],
       [ 0.20698548, -4.81274701,  2.90348343,  4.22852925, -1.93502761,
         0.08684097,  0.63637024,  1.34539204,  1.92582796,  0.39527086,
        -1.84302689, -0.26067534, -3.43039347]])

In [22]:
pca.components_

array([[ 1.54039724e-03, -3.31317209e-03, -4.98705214e-04, ...,
         1.21203415e-03,  2.40823504e-03,  7.25021860e-04],
       [ 6.24699075e-04, -5.20911580e-05,  1.81778520e-03, ...,
        -4.96668200e-04, -2.79839328e-03, -9.68680298e-04],
       [-3.50262657e-03, -2.92443273e-03, -1.44157432e-03, ...,
         2.61295130e-03,  9.21444889e-04, -1.50150804e-03],
       ...,
       [ 2.03743060e-03, -1.54590444e-03, -5.55904307e-03, ...,
         2.74908641e-04, -2.91461963e-03, -1.74995762e-04],
       [-5.01122792e-03,  1.13915848e-02, -2.93677189e-03, ...,
         1.05245721e-04,  1.73396751e-03,  1.73019206e-03],
       [ 6.15303795e-03, -2.32066710e-03, -2.85760197e-03, ...,
        -6.46224535e-03,  1.26188523e-03,  2.58934388e-03]])

In [21]:
pca.n_components_

13

In [23]:
X_pca_test = pca.transform(X_sc_test)
X_pca_test

array([[ 2.6491316 , -0.75974154,  7.93754891, ...,  1.64721785,
         1.8857297 , -1.97130382],
       [-1.55785053,  3.56492638, -1.64061527, ..., -3.02679   ,
        -1.97377365,  1.36121021],
       [-3.06767872,  5.21224128, -1.97658852, ..., -2.18662984,
         1.31071074,  1.54193635],
       ...,
       [-1.71394589,  2.19339732,  3.36030249, ..., -0.34881392,
         0.04000389,  0.32146327],
       [11.29534561, -0.64661267,  2.9625681 , ..., -1.59349459,
         0.74569828,  0.71080007],
       [ 3.58384581,  3.95782724,  6.30025409, ...,  3.87922446,
         0.85645358,  1.47063532]])

In [24]:
fig = px.imshow(pca.inverse_transform(X_pca_train[0:10]).reshape(10, 28, 28), binary_string=True, facet_col=0, facet_col_wrap=5)
fig.show()


### We notice that the noise has been significantly reduced

### Let's train a SVM model to see the effects of PCA 

In [26]:
svc.fit(X_pca_train, y_train)
svc.score(X_pca_test, y_test)


[LibSVM]

0.8999047619047619

### We notice that the accuracy improved and the training took wayyy less time! So the PCA was effective !!